import Image from "next/image";
import Link from "next/link";

const values = [["Purity", "Every gram is tested, hallmarked, and held to our uncompromising standard."], ["Craft", "Human hands, inherited knowledge, and patience give each piece its soul."], ["Trust", "Transparent guidance and enduring relationships have defined us for six decades."]];
export const metadata = { title: "About Us" };
export default function AboutPage() { return <main>
  <section className="bg-burgundy px-5 py-24 text-center text-cream"><p className="eyebrow">Our story, our promise</p><h1 className="mt-4 font-serif text-5xl md:text-7xl">About Jewellers Petlawad Wala</h1><p className="mx-auto mt-6 max-w-2xl leading-7 text-cream/70">A family heritage shaped by artistry, integrity, and an enduring devotion to the finest Indian jewelry.</p></section>
  <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 md:grid-cols-2"><div className="relative aspect-[4/3]"><Image src="/images/gold/17.jpeg" alt="Jeweller crafting an intricate gold piece" fill sizes="(max-width:768px) 100vw, 50vw" className="object-cover" /></div><div><p className="eyebrow">Since 1961</p><h2 className="mt-3 font-serif text-4xl text-burgundy md:text-5xl">A Heritage Written in Gold</h2><p className="prose-copy mt-5">What began as a modest family atelier in Petlawad has grown into a trusted destination for remarkable gold and silver jewelry. Through every generation, the same principles have guided us: honest purity, patient craftsmanship, and personal service.</p><p className="prose-copy mt-4">Today, our Ratlam boutique brings traditional artistry into conversation with a refined contemporary sensibility.</p></div></section>
  <section className="bg-cream px-5 py-20"><div className="section-heading"><p className="eyebrow">What guides us</p><h2>Our Core Values</h2></div><div className="mx-auto mt-12 grid max-w-6xl gap-px bg-linen md:grid-cols-3">{values.map(([title, copy], i) => <article className="bg-white p-10" key={title}><span className="font-serif text-4xl text-gold">0{i+1}</span><h3 className="mt-8 font-serif text-2xl text-burgundy">{title}</h3><p className="mt-4 text-sm leading-6 text-slate">{copy}</p></article>)}</div></section>
  <section className="px-5 py-20"><div className="section-heading"><p className="eyebrow">The people behind every piece</p><h2>Generations of Expertise</h2></div><div className="mx-auto mt-12 grid max-w-4xl gap-8 sm:grid-cols-2">{[["Shri Petlawad Wala", "Founder & Visionary", "/images/gold/18.png"], ["The Atelier Team", "Master Karigars", "/images/gold/20.png"]].map(([name, role, image]) => <article key={name}><div className="relative aspect-[4/3] overflow-hidden bg-mist"><Image src={image} alt={name} fill sizes="(max-width:640px) 100vw, 50vw" className="object-cover" /></div><h3 className="mt-5 font-serif text-2xl text-burgundy">{name}</h3><p className="mt-1 text-xs uppercase tracking-widest text-gold">{role}</p></article>)}</div></section>
  <section className="bg-cream px-5 py-20"><div className="mx-auto grid max-w-6xl items-center gap-12 md:grid-cols-2"><div><p className="eyebrow">A personal welcome</p><h2 className="mt-3 font-serif text-4xl text-burgundy">Visit Our Boutique</h2><p className="prose-copy mt-5">Discover our collections at leisure and receive considered, personal guidance from our family. Private bridal and custom-design consultations are available by appointment.</p><Link href="/contact" className="button-primary mt-7">Plan your visit</Link></div><div className="relative aspect-[4/3]"><Image src="/images/gold/16.png" alt="Jewellers Petlawad Wala boutique collection" fill sizes="(max-width:768px) 100vw, 50vw" className="object-cover" /></div></div></section>
  </main>; }
