import Link from "next/link";

const contacts = [
  ["WhatsApp", "Speak directly with our jewelry concierge.", "Start a conversation", "https://wa.me/919876543210", "W"],
  ["Instagram", "Follow new collections and atelier stories.", "Follow us", "https://instagram.com", "I"],
  ["YouTube", "Watch the craft and heritage behind each piece.", "Visit channel", "https://youtube.com", "Y"]
];
export const metadata = { title: "Contact" };
export default function ContactPage() { return <main>
  <section className="bg-burgundy px-5 py-24 text-center text-cream"><p className="eyebrow">We would love to hear from you</p><h1 className="mt-4 font-serif text-6xl md:text-7xl">Get In Touch</h1><p className="mx-auto mt-6 max-w-xl text-cream/70">Whether you are searching for an heirloom, planning a bridal appointment, or dreaming of a custom piece, our team is here to help.</p></section>
  <section className="px-5 py-20"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-3">{contacts.map(([name, copy, action, href, icon]) => <a href={href} key={name} className="group border border-linen p-9 text-center hover:border-gold"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border border-gold font-serif text-xl text-gold">{icon}</span><h2 className="mt-6 font-serif text-2xl text-burgundy">{name}</h2><p className="mt-3 text-sm leading-6 text-slate">{copy}</p><span className="mt-5 inline-block text-[10px] font-bold uppercase tracking-widest text-gold">{action} →</span></a>)}</div></section>
  <section className="bg-cream px-5 py-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2"><div><p className="eyebrow">Our showroom</p><h2 className="mt-3 font-serif text-4xl text-burgundy">Come See Us in Ratlam</h2><p className="prose-copy mt-5">Step into a calm, personal setting where our team can guide you through our collections and help you find a piece with meaning.</p><dl className="mt-8 grid gap-6 border-t border-linen pt-8 sm:grid-cols-2"><div><dt className="eyebrow">Address</dt><dd className="mt-2 text-sm leading-6">171, Chandni Chowk<br />Ratlam, Madhya Pradesh 457001</dd></div><div><dt className="eyebrow">Phone</dt><dd className="mt-2 text-sm"><a href="tel:+919876543210">+91 98765 43210</a></dd></div><div><dt className="eyebrow">Email</dt><dd className="mt-2 text-sm"><a href="mailto:contact@jpjewellers.com">contact@jpjewellers.com</a></dd></div><div><dt className="eyebrow">Boutique hours</dt><dd className="mt-2 text-sm leading-6">Monday–Saturday: 10 AM–8 PM<br />Sunday: 11 AM–6 PM</dd></div></dl><Link href="mailto:contact@jpjewellers.com" className="button-primary mt-8">Email the atelier</Link></div>
  <div className="relative min-h-[430px] overflow-hidden border border-linen bg-white"><div className="absolute inset-0 bg-[linear-gradient(90deg,transparent_49%,#e8e3dc_50%,transparent_51%),linear-gradient(transparent_49%,#e8e3dc_50%,transparent_51%)] bg-[size:90px_90px]"/><div className="absolute left-[55%] top-[48%] flex -translate-x-1/2 -translate-y-1/2 flex-col items-center"><span className="h-7 w-7 rounded-full border-[7px] border-white bg-burgundy shadow-lg"/><span className="mt-3 bg-white px-4 py-2 text-center text-xs font-bold text-burgundy shadow">Jewellers Petlawad Wala<br /><small className="font-normal text-slate">Chandni Chowk, Ratlam</small></span></div><span className="absolute bottom-5 left-5 text-[10px] font-bold uppercase tracking-widest text-gold">23.3315° N, 75.0367° E</span></div></div></section>
  </main>; }
