import Image from "next/image";
import { ProductCard } from "@/components/ProductCard";
import { TrustStrip } from "@/components/TrustStrip";
import { goldProducts } from "@/data/products";

export const metadata = { title: "Royal Kundan Bridal Necklace Set" };
const thumbs = ["02.jpeg", "03.png", "06.png", "08.png"];
export default function ProductPage() { return <main>
  <section className="bg-cream px-5 py-16"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><div className="relative aspect-square overflow-hidden rounded-sm bg-white"><Image src="/images/gold/02.jpeg" alt="Royal Kundan Bridal Necklace Set on a dark bust" fill priority sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" /></div><div className="mt-4 grid grid-cols-4 gap-3">{thumbs.map((image, i) => <div className="relative aspect-[4/3] overflow-hidden border border-linen bg-white" key={image}><Image src={`/images/gold/${image}`} alt={`Royal Kundan necklace view ${i + 1}`} fill sizes="120px" className="object-cover" /></div>)}</div></div>
  <div className="lg:pt-3"><div className="flex flex-wrap items-center gap-2"><span className="eyebrow">BIS 22K Hallmarked</span><span className="text-linen">•</span><span className="text-xs text-slate">Bridal Heritage</span></div><h1 className="mt-4 font-serif text-5xl leading-tight text-burgundy md:text-6xl">Royal Kundan Bridal Necklace Set</h1><p className="mt-5 leading-7 text-slate">A magnificent heirloom masterpiece. Handcrafted in pure 22K gold, adorned with custom-set Kundan stones, pristine Meenakari borders, and delicate hanging ocean-fresh pearls.</p><div className="mt-8 border-y border-linen py-6"><p className="text-[10px] font-bold uppercase tracking-widest text-slate">Estimated valuation (incl. of all taxes)</p><p className="mt-2 font-serif text-4xl font-bold text-burgundy">₹3,45,000 <span className="font-sans text-xs font-normal text-gold">(Gold Standard Investment)</span></p></div><dl className="grid gap-4 border-b border-linen py-6 text-sm sm:grid-cols-2"><div><dt className="text-slate">Metal Type</dt><dd className="mt-1 font-bold">22kt Yellow Gold</dd></div><div><dt className="text-slate">Net Weight</dt><dd className="mt-1 font-bold">85.00 Grams</dd></div><div><dt className="text-slate">Stone Details</dt><dd className="mt-1 font-bold">Premium Kundan, Basra Pearls</dd></div><div><dt className="text-slate">Certification</dt><dd className="mt-1 font-bold text-gold">BIS Hallmark Certified</dd></div></dl><div className="mt-7 grid gap-3 sm:grid-cols-2"><a href="tel:+919876543210" className="button-primary">☎ Contact us</a><a href="https://wa.me/919876543210" className="button-outline">○ Continue to WhatsApp</a></div></div></div></section>
  <section className="px-5 py-20"><div className="mx-auto max-w-7xl"><p className="border-b border-linen pb-5 text-xs font-bold uppercase tracking-widest text-burgundy">Description</p><div className="mt-9 grid gap-12 lg:grid-cols-[1.8fr_1fr]"><div><h2 className="font-serif text-3xl text-burgundy">An Undying Legacy of Rajasthani Artistry</h2><p className="prose-copy mt-5">Crafted meticulously over 120 man-hours by our premier generation of Karigars, the Royal Kundan Bridal Set represents the pinnacle of heritage bridal luxury. Kundan, the ancient method of setting gemstones with refined gold foil between stones and mountings, dates back centuries to royal Mughal and Rajasthani courts.</p><p className="prose-copy mt-4">Each stone is hand-selected for symmetry and clarity, framed with brilliant red and green enamel meenakari backing. This ensures the necklace is breathtaking from every angle.</p></div><aside className="bg-cream p-8"><h3 className="font-serif text-xl text-burgundy">Highlights</h3><ul className="mt-4 space-y-3 text-sm">{["100% certified BIS 22kt purity gold.", "Intricate ancient hand-done Meenakari detailing.", "Specially selected, pristine hanging Basra Pearls.", "Complete and secure Lifetime Exchange Guarantee."].map(x => <li className="flex gap-3" key={x}><span className="text-gold">✣</span>{x}</li>)}</ul></aside></div></div></section>
  <TrustStrip dark />
  <section className="px-5 py-20"><div className="section-heading"><p className="eyebrow">Complementary masterpieces</p><h2>You May Also Like</h2></div><div className="mx-auto mt-12 grid max-w-7xl gap-6 sm:grid-cols-2 lg:grid-cols-4">{goldProducts.slice(0,4).map(p => <ProductCard key={p.name} product={p} />)}</div></section>
  <section className="bg-cream px-5 py-16"><div className="mx-auto max-w-7xl"><h2 className="font-serif text-3xl text-burgundy">Recently Viewed</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{goldProducts.slice(4,7).map(p => <article className="flex items-center gap-4 border border-linen bg-white p-3" key={p.name}><div className="relative h-20 w-20 shrink-0"><Image src={p.image} alt={p.name} fill sizes="80px" className="object-cover" /></div><div><h3 className="font-serif text-sm text-burgundy">{p.name}</h3><p className="mt-1 text-xs font-bold">{p.price}</p><span className="text-[9px] uppercase tracking-widest text-gold">22K Gold</span></div></article>)}</div></div></section>
  </main>; }
