import Image from "next/image";
import Link from "next/link";
import { TrustStrip } from "@/components/TrustStrip";

const terms = [
  ["Site Use", "This website is provided for informational purposes only. By accessing or using it, you agree to use these pages for personal, non-commercial use."],
  ["Informational Content", "Our content is general information and may change without notice. We strive for accuracy but do not guarantee completeness or suitability for every purpose."],
  ["Privacy & Cookies", "We use cookies and similar technologies to improve your browsing experience and understand how visitors use this website."],
  ["External Links", "Links to third-party websites may appear for convenience. We are not responsible for their content, accuracy, or privacy practices."],
  ["Updates", "We may update these terms at any time without notice. Continued use after an update means you accept the revised terms."],
  ["Contact", "Questions about these terms may be directed to contact@jpjewellers.com."]
];

export default function HomePage() {
  return <main>
    <section className="grid min-h-[640px] bg-cream lg:grid-cols-2"><div className="relative min-h-[420px]"><Image src="/images/gold/19.png" alt="Handcrafted Indian gold necklace" fill priority sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /></div><div className="flex items-center px-7 py-16 lg:px-20"><div className="max-w-xl"><p className="eyebrow">Since 1961</p><h1 className="mt-4 font-serif text-5xl leading-[.98] text-burgundy md:text-7xl">Timeless Elegance,<br />Crafted for You</h1><p className="mt-6 max-w-lg leading-7 text-slate">Discover handcrafted gold and silver jewelry shaped by generational craftsmanship, uncompromising purity, and a legacy of trust.</p><Link href="/gold" className="mt-8 inline-block border-b border-burgundy pb-1 text-xs font-bold uppercase tracking-[.15em] text-burgundy">Shop collection →</Link></div></div></section>
    <section className="px-5 py-20"><div className="section-heading"><p className="eyebrow">The signature pieces</p><h2>Featured Collections</h2></div><div className="mx-auto mt-12 grid max-w-6xl gap-8 md:grid-cols-2">{[["Gold Collection", "/images/gold/08.png", "/gold"], ["Silver Collection", "/images/silver/01.png", "/silver"]].map(([name, image, href]) => <Link href={href} key={name} className="group"><div className="relative aspect-[4/3] overflow-hidden bg-mist"><Image src={image} alt={name} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition duration-700 group-hover:scale-105" /></div><div className="mt-4 flex items-center justify-between"><h3 className="font-serif text-2xl text-burgundy">{name}</h3><span className="text-[10px] font-bold uppercase tracking-widest">View collection →</span></div></Link>)}</div></section>
    <section className="bg-cream"><div className="mx-auto grid max-w-7xl md:grid-cols-2"><div className="relative min-h-[440px]"><Image src="/images/gold/17.jpeg" alt="Master jeweller handcrafting an heirloom" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div><div className="flex items-center px-7 py-16 md:px-16"><div><p className="eyebrow">Our heritage</p><h2 className="mt-3 font-serif text-4xl text-burgundy">A Legacy of Craftsmanship<br />Since 1961</h2><p className="prose-copy mt-5">Creating everlasting jewelry since 1961, our creations embody classic luxury, meticulous detail, and absolute purity of gold and silver.</p><Link href="/about-us" className="mt-6 inline-block text-xs font-bold uppercase tracking-widest text-burgundy">Discover our story →</Link></div></div></div></section>
    <section className="px-5 py-20"><div className="section-heading"><p className="eyebrow">The JP standards</p><h2>Why Choose Us</h2></div><div className="mx-auto mt-10 max-w-5xl divide-y divide-linen">{[["01", "Certified Purity", "Every piece is hallmarked and authenticated."], ["02", "Handcrafted Excellence", "Designed by visionary artists and shaped by generational karigars."], ["03", "Trusted Heritage", "Six decades of honesty and enduring craftsmanship."]].map(([n, title, copy]) => <div className="grid gap-4 py-7 sm:grid-cols-[70px_220px_1fr]" key={n}><span className="font-serif text-2xl text-gold">{n}</span><h3 className="font-serif text-xl text-burgundy">{title}</h3><p className="text-sm leading-6 text-slate">{copy}</p></div>)}</div></section>
    <TrustStrip dark />
    <section className="bg-burgundy px-5 py-20 text-cream"><div className="mx-auto grid max-w-6xl items-center gap-12 md:grid-cols-2"><div><p className="eyebrow">Made around you</p><h2 className="mt-3 font-serif text-5xl italic">Design Your Dream Jewellery</h2><p className="mt-5 max-w-md leading-7 text-cream/70">Share your idea with our master craftsmen on WhatsApp. Describe your design, send references, and we will bring your dream piece to life.</p><a href="https://wa.me/919876543210" className="mt-7 inline-flex bg-gold px-6 py-3 text-xs font-bold uppercase tracking-widest text-burgundy">Chat on WhatsApp</a></div><div className="relative aspect-[4/3] overflow-hidden rounded-sm"><Image src="/images/gold/20.png" alt="Custom gold jewelry consultation" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div></div></section>
    <section className="bg-cream px-5 py-20"><div className="mx-auto max-w-6xl"><h2 className="font-serif text-4xl text-burgundy">Visit Us</h2><div className="mt-8 grid gap-8 border-t border-linen pt-8 md:grid-cols-2"><address className="not-italic text-sm leading-7 text-slate"><b className="eyebrow">Address</b><br />171, Chandni Chowk, Ratlam,<br />Madhya Pradesh — 457001<br /><br /><a href="mailto:contact@jpjewellers.com">contact@jpjewellers.com</a><br /><a href="tel:+919876543210">+91 98765 43210</a></address><div className="relative min-h-64 overflow-hidden border border-linen bg-white"><div className="absolute inset-0 bg-[linear-gradient(90deg,transparent_49%,#e8e3dc_50%,transparent_51%),linear-gradient(transparent_49%,#e8e3dc_50%,transparent_51%)] bg-[size:80px_80px]"/><div className="absolute left-1/2 top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-white bg-burgundy shadow-md"/><p className="absolute left-5 top-5 text-xs font-bold uppercase tracking-widest text-burgundy">Ratlam<br /><span className="font-normal normal-case text-slate">Chandni Chowk</span></p></div></div></div></section>
    <section className="bg-cream px-5 pb-20"><div className="mx-auto max-w-6xl"><p className="eyebrow">Website terms</p><h2 className="mt-3 font-serif text-4xl text-burgundy">Terms &amp; Conditions</h2><div className="mt-8 divide-y divide-linen border-t border-linen">{terms.map(([title, copy]) => <div className="py-6" key={title}><h3 className="font-serif text-lg text-burgundy">{title}</h3><p className="mt-2 text-xs leading-6 text-slate">{copy}</p></div>)}</div></div></section>
  </main>;
}
